### ISSUE TITLE
Deberes para día 3 Febrero

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/daily#3]
Completar el controlador `create` para que funcione. Es decir, que persista el `Member` en mongo.

**Comment by cervi** [comment]
@joserobleda , estoy con los ejericios, pero hay una cosa que no entiendo
en la vista team.tml  tenemos el sig formulario
`<form ng-submit="createMember()">
		Create new member:
		<input type="text" ng-model="newMember" />
	</form>
`

Entiendo que le estamos asignando el modelo NewMember ,en la carpeta de modelos, tenemos el member.js, pero en ningún punto veo newMember... 

Aparte, en el submit llama a la funcion createMember, pero no está en ningún lado...
Creo que o me he perdido algo, no?

**Comment by joserobleda** [comment]
Me hablas del código del lado del cliente, los deberes son para el lado del servidor, no hay que hacer nada con angular, ni con html ni nada... es todo node y mongo

Lo que hay que hacer es un `POST /member` (como puedas quieras) y almacenar en la bbdd, como lo hace el controller `save`

**Comment by cervi** [comment]
pero en realidad, el `create` seria el `save` actual, no? lo único que en vez de crearlo a mano cuando pones 
`new Member {
name: "jose"}` habría que recuperar los datos del html. o voy muy desencaminado?

**Comment by joserobleda** [comment]
Create es para crear por primera vez (lo necesitamos por la complejidad de la que hablamos el otro día) y save es para guardar algo que ya existe. Deben existir ambos.

Olvida el lado del cliente, no hay HTML aquí. Solo es necesario hacer una petición POST

**Comment by joserobleda** [comment]
Para hacer un POST, puedes hacer un formulario, o bien usar alguna libreria o algo, esta va muy bien y se instala en chrome: https://chrome.google.com/webstore/detail/postman-rest-client/fdmmgilgnpjigdojojpjoooidkmcomcm?hl=en
