### ISSUE TITLE
Deberes para día 3 de Marzo

### ISSUE THREAD

**Issue by joserobleda** [joserobleda/daily#6]
- [x] No permitir duplicar email al editar
   - [x] Buscar la forma de no duplicar código

- [x] Crear tarea, mostrar, editar y borrar tarea. No hace falta validar los datos.

**Comment by cervi** [comment]
Para las validaciones
http://www.ng-newsletter.com/posts/validations.html

**Comment by joserobleda** [comment]
Muy bueno!

**Comment by joserobleda** [comment]
Nos ha faltado "borrar y editar tareas" así que dejo abiertos los deberes.

**Comment by joserobleda** [comment]
A terminar esta @albertoprad, @LdonosoC, @cervi

**Comment by joserobleda** [comment]
Terminar el método "delete"
